### ISSUE TITLE
Pirate missions cause crash and save corrupt

### ISSUE THREAD

**Issue by Udrakan** [Udrakan/baroita#16]
![image](https://user-images.githubusercontent.com/59519434/124048377-80cd3580-da16-11eb-8566-707991accc4c.png)
https://steamcommunity.com/workshop/filedetails/discussion/2005463692/2999926461245043974/?ctp=7

**Comment by Udrakan** [comment]
tested pirate mission with typhon pirate
working correctly.
Other pirate sub might be causing this

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/124049010-deae4d00-da17-11eb-9e1e-f89fffc370aa.png)

**Comment by Runolv** [comment]
Missions overriding need to be removed.
