### ISSUE TITLE
Clothier shop

### ISSUE THREAD

**Issue by Runolv** [Udrakan/baroita#31]
- [x] ita_picker still left in the code and causing errors.
![image](https://user-images.githubusercontent.com/86156115/127238939-09051f26-db6d-427f-8464-2119e6059646.png)
- [x] When buying tool belt without enough money, they will not be returned. (Seems to be broken shop event loop)
- [x] Trader leaving his hull.
- [x] Removing lower hatch decor when hatch not in use.

**Comment by Udrakan** [comment]
Broken loop for more traders. Got to take a look into it.
