### ISSUE TITLE
Bad airlock

### ISSUE THREAD

**Issue by Udrakan** [Udrakan/baroita#42]
Station with 2 docks
![image](https://user-images.githubusercontent.com/59519434/133948557-915bde78-d6fa-47ce-95e5-662ef9457301.png)

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/133948587-e1c664a2-5f9b-49a4-b3b7-941e0c155881.png)

**Comment by Runolv** [comment]
Already changed
